spring.application.name=api-rest-take-home

# Database configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/trx_api_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging configuration with traceId from MDC
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-no-trace}] %-5level %logger{36} - %msg%n
